productor_consumer:productor_consumer.cpp
	g++ -std=c++11 $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread
join_pthread:join_pthread.c
	gcc $^ -o $@ -lpthread
exit_pthread:exit_pthread.c
	gcc $^ -o $@ -lpthread
create_pthread:create_pthread.c
	gcc $^ -o $@ -lpthread
